# Generated by Django 5.1 on 2024-09-07 19:59

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to=account.models.user_directory_path
            ),
        ),
    ]
